server:
  port: 8887 # 服务端口

eureka:
  instance:
    hostname: server3 # 设置主机名
  client:
    registerWithEureka: false # 是否向 Eureka 注册服务。该应用为服务注册中心，不需要自注册，设置为 false
    fetchRegistry: false      # 是否检索服务。该应用为服务注册中心，职责为注册和发现服务，无需检索服务，设置为 false
    serviceUrl:
      defaultZone: http://server1:8888/eureka/,http://server2:8889/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0 # 设置同步为空时的等待时间。默认 5 * MINUTES